// Zero-copy access to the compiled playing card (sim/_cards.pyx, a Cython "api" class): the C++ core
// reads its fields straight from the object. Enhancement, edition and seal are Python strings; they are
// mapped to small codes by comparing with the canonical values.
#pragma once
#include <Python.h>
#include "../_cards.h"      // struct CardObject (generated by the Cython build)

namespace balatro {

enum Enh { E_NONE = 0, E_BONUS, E_MULT, E_WILD, E_GLASS, E_STEEL, E_STONE, E_GOLD, E_LUCKY, E_HIDDEN, E_OTHER };
enum Edition { ED_NONE = 0, ED_FOIL, ED_HOLO, ED_POLY, ED_NEG, ED_OTHER };
enum Seal { S_NONE = 0, S_RED, S_BLUE, S_GOLD, S_PURPLE, S_OTHER };

inline bool str_is(PyObject* s, const char* lit, Py_ssize_t n) {
    if (PyUnicode_GET_LENGTH(s) != n) return false;
    return PyUnicode_CompareWithASCIIString(s, lit) == 0;
}

inline int enh_code(PyObject* s) {
    Py_ssize_t n = PyUnicode_GET_LENGTH(s);
    if (n == 0) return E_NONE;
    switch (PyUnicode_READ_CHAR(s, 0)) {
        case 'B': return str_is(s, "BONUS", 5) ? E_BONUS : E_OTHER;
        case 'M': return str_is(s, "MULT", 4) ? E_MULT : E_OTHER;
        case 'W': return str_is(s, "WILD", 4) ? E_WILD : E_OTHER;
        case 'G': return str_is(s, "GLASS", 5) ? E_GLASS : (str_is(s, "GOLD", 4) ? E_GOLD : E_OTHER);
        case 'S': return str_is(s, "STEEL", 5) ? E_STEEL : (str_is(s, "STONE", 5) ? E_STONE : E_OTHER);
        case 'L': return str_is(s, "LUCKY", 5) ? E_LUCKY : E_OTHER;
        case 'H': return str_is(s, "HIDDEN", 6) ? E_HIDDEN : E_OTHER;
        default: return E_OTHER;
    }
}

inline int edition_code(PyObject* s) {
    Py_ssize_t n = PyUnicode_GET_LENGTH(s);
    if (n == 0) return ED_NONE;
    switch (PyUnicode_READ_CHAR(s, 0)) {
        case 'F': return str_is(s, "FOIL", 4) ? ED_FOIL : ED_OTHER;
        case 'H': return str_is(s, "HOLO", 4) ? ED_HOLO : ED_OTHER;
        case 'P': return str_is(s, "POLYCHROME", 10) ? ED_POLY : ED_OTHER;
        case 'N': return str_is(s, "NEGATIVE", 8) ? ED_NEG : ED_OTHER;
        default: return ED_OTHER;
    }
}

inline int seal_code(PyObject* s) {
    Py_ssize_t n = PyUnicode_GET_LENGTH(s);
    if (n == 0) return S_NONE;
    switch (PyUnicode_READ_CHAR(s, 0)) {
        case 'R': return str_is(s, "RED", 3) ? S_RED : S_OTHER;
        case 'B': return str_is(s, "BLUE", 4) ? S_BLUE : S_OTHER;
        case 'G': return str_is(s, "GOLD", 4) ? S_GOLD : S_OTHER;
        case 'P': return str_is(s, "PURPLE", 6) ? S_PURPLE : S_OTHER;
        default: return S_OTHER;
    }
}

// A card as the C++ code sees it: the fields decoded once
struct CardView {
    int rank, suit, enh, ed, seal, extra;
    bool deb, hidden;
    long long uid;
    CardObject* obj;

    static CardView of(PyObject* o) {
        CardObject* c = (CardObject*)o;
        CardView v;
        v.rank = c->rank; v.suit = c->suit; v.enh = enh_code(c->enh); v.ed = edition_code(c->edition);
        v.seal = seal_code(c->seal); v.extra = c->extra_chips; v.deb = c->debuffed != 0;
        v.hidden = c->hidden != 0; v.uid = c->uid; v.obj = c;
        return v;
    }
    bool is_stone() const { return enh == E_STONE || enh == E_HIDDEN; }
    int chip_value() const {
        if (enh == E_HIDDEN) return 0;
        if (enh == E_STONE) return 50;
        if (rank == 14) return 11;
        return rank < 10 ? rank : 10;
    }
    bool is_face(bool pareidolia, bool from_boss = false) const {
        if (is_stone() || (deb && !from_boss)) return false;
        return pareidolia || (rank >= 11 && rank <= 13);
    }
    bool has_suit(int s, bool smeared) const {
        if (is_stone()) return false;
        if (enh == E_WILD) return true;
        if (smeared) return (suit % 2) == (s % 2);
        return suit == s;
    }
    bool flush_suit(int s, bool smeared) const {
        if (is_stone()) return false;
        if (enh == E_WILD && !deb) return true;
        if (smeared) return (suit % 2) == (s % 2);
        return suit == s;
    }
    bool live_suit(int s, bool smeared) const { return !deb && has_suit(s, smeared); }
};

}  // namespace balatro
